language: haskell
ghc:
  - 7.4
  - 7.6
  - 7.8
  - 8.0
  - 8.2
  - 8.4
  - 8.6
install:
  - cabal install happy-1.19.5
  - cabal install --only-dependencies --enable-tests
script:
  - cabal configure && cabal build
